### PR TITLE
Do not let `_cap_cup` set `_eol` to True

### PR DESCRIPTION
**Pull request by eugulixes**

### CODE REVIEW

**Review by dshil — COMMENTED** [review]
@eugulixes, can we squash commits 7d1c3e4, 6b75521 into one?

**Comment by eugulixes** [comment]
@dshil, they are not connected with each other. However, I rearranged the list of commits and combined the first one (bug fix) and the latest one (test fix) into a single commit.

**Comment by eugulixes** [comment]
@dshil, it's ready to be reviewed again and merged.

**Review by dshil — APPROVED** [review]
LGTM

**Pull request merged**
