### PR TITLE
Documentation: use rst instead of md

### PR DESCRIPTION
**Pull request by eugulixes**
The current version of README is simplified in comparison with the previous one. Additional information will be moved to docs/index.rst and other rst files in the docs directory.

### CODE REVIEW

**Comment by dshil** [comment]
Can you give back AUTHORS to README?

**Comment by dshil** [comment]
@eugulixes when we go to `npm search` or to `PyPI` we have a reference to the old repository name `github.com/Tolstoyevsky/gits`. 

Can we fix it in this PR?

**Comment by eugulixes** [comment]
@dshil `github.com/Tolstoyevsky/gits` is still relevant. I'll fix it in a different PR.

**Review by dshil — APPROVED** [review]
LGTM

**Pull request merged**
