### PR TITLE
Remove some test stubs

### PR DESCRIPTION
**Pull request by dshil**

### CODE REVIEW

**Comment by eugulixes** [comment]
@dshil 
Strictly speaking they are not tests. What about the following commit message:

> Remove some test stubs
> 
> The stubs are not supposed to be implemented.

Also It seems to me that `test_cap_smso_rev` should be removed here as well. I saw you had removed it in one of the latest PRs, but I feel it should be done here.

**Comment by eugulixes** [comment]
Also I think we have to remove the `test_cap_dch1` stub since `dch1` is only `dch` with input parameter 1, so we can check both `dch` and `dch1` in `test_cap_dch`.

**Comment by dshil** [comment]
ping @eugulixes, about deleting the `test_cap_dch1`. I don't like the idea.
There are 2 possible cases:
- `cap_dch` will be changed and `cap_dch1` has stopped be a special case of a `cap_dch`.
- `cap_dch1` will be changed and we'll not have a corresponding test.

**Comment by eugulixes** [comment]
@dshil, agreed.

**Review by eugulixes — APPROVED** [review]

**Pull request merged**
